### ISSUE TITLE
ERROR: The mail binary does not exist in $mail.

### ISSUE THREAD

**Issue by abacao** [click0/domain-check-2#30]
Hello,

I'm getting the following error

```
./domain-check-2.sh -d google.com                                                                                                                                                          
ERROR: The mail binary does not exist in $mail.
  FIX: Please modify the $mail variable in the program header.
```

**Comment by click0** [comment]
> Hello,
> 
> I'm getting the following error
> 
> ```
> ./domain-check-2.sh -d google.com                                                                                                                                                          
> ERROR: The mail binary does not exist in $mail.
>   FIX: Please modify the $mail variable in the program header.
> ```

Your Linux system is missing a mailutils package. The GNU mailutils package contains various utilities for handling mail. Run the following [linux command](https://linuxconfig.org/linux-commands) to install mailutils package:

`# apt-get install mailutils`
