### ISSUE TITLE
Support for .bm domains

### ISSUE THREAD

**Issue by fruchtereric32** [click0/domain-check-2#31]
From what I can tell, the script doesn't support *.bm domains. Are there are any plans to include such support? It would be extremely helpful for my usage of it.

**Comment by click0** [comment]
Please show examples of such domains.
For example, `gov.bm` does not have a domain expiration date.

**Comment by fruchtereric32** [comment]
Sure. An example would be https://www.gibbons.bm/

**Comment by click0** [comment]
> Sure. An example would be https://www.gibbons.bm/

As long as you use it like this. I will find time and fix the script.

```
# sh domain-check-2.sh -s whois.bermudanic.bm -d gibbons.bm

Domain                              Registrar                                      Status   Expires     Days Left
----------------------------------- ---------------------------------------------- -------- ----------- ---------
gibbons.bm                          https                                          Valid    07-jan-2024 368

```

**Comment by fruchtereric32** [comment]
Sure I can do that. Thanks

**Comment by click0** [comment]
Added support for .bm domain.
db7001719baedc5f83b8110220964e0263b2bac4
