### ISSUE TITLE
BINARY Error on Ubuntu 

### ISSUE THREAD

**Issue by ajnasaboobacker** [click0/domain-check-2#32]
### Steps followed:

```
Git clone https://github.com/click0/domain-check-2.git
cd domain-check-2
chmod +x domain-check2.sh 
./domain-check2.sh -f domain-list.txt
```

### Error while running the script:

ERROR: The mail binary does not exist in $mail.
  FIX: Please modify the $mail variable in the program header.

### Architecture: arm64

**Comment by click0** [comment]
Your Linux system is missing a mailutils package. The GNU mailutils package contains various utilities for handling mail. Run the following [linux command](https://linuxconfig.org/linux-commands) to install mailutils package:

`# apt-get install mailutils`

The script has a [list of dependencies](https://github.com/click0/domain-check-2#requirements
).

**Comment by jherazob** [comment]
I think the issue is that the script does this regardless of whether you plan to send email or not, it makes sense that it crashes if you tell it to send email and it's missing the mail binary, but if you don't it shouldn't crash

**Comment by click0** [comment]
Removed the check for the existence of the mail client binary if the script does not use mail notification.
af637b047b9c35684a02f35665e8a2af02a29f61

Please test.
