### ISSUE TITLE
.li .ch zone

### ISSUE THREAD

**Issue by Satrier** [click0/domain-check-2#37]
In  **.li** and **.ch** zone only First registration date + 1 year for expire

```
whois speed.li
This information is subject to an Acceptable Use Policy.
See https://www.nic.ch/terms/aup/


Domain name:
speed.li

Registrar:
METANET AG
Josefstrasse 218
CH-8005 Zürich
Switzerland

First registration date:
2001-03-09

DNSSEC:Y

Name servers:
ns1.newsnet.li  [2a00:f8c0:8000::224]
ns1.newsnet.li  [5.34.248.224]
ns2.newsnet.at
ns3.newsnet.me
```

**Comment by click0** [comment]
```
whois speed.li
...
# whois.nic.li

Requests of this client are not permitted. Please use https://www.nic.ch/whois/ for queries.

```

```
whois speed.ch
...
# whois.nic.ch

Requests of this client are not permitted. Please use https://www.nic.ch/whois/ for queries.

```

Both domain zones have disabled the native whois service. 
They have a web version of the whois service, but with captcha and without private personal data.

Please note: Since 1 January 2021, personal data associated with registered domain names is no longer disclosed. Information about holders of domain names can only be obtained in exceptional cases.

**Comment by Satrier** [comment]
on Debian 11 whois works well, but only with the First registration date
![image](https://github.com/click0/domain-check-2/assets/10636815/574a9121-6d80-405d-9b9c-24ca1f376a46)

**Comment by click0** [comment]
> on Debian 11 whois works well, but only with the First registration date ![image](https://private-user-images.githubusercontent.com/10636815/293162839-574a9121-6d80-405d-9b9c-24ca1f376a46.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3ODc2NDcsIm5iZiI6MTcwMzc4NzM0NywicGF0aCI6Ii8xMDYzNjgxNS8yOTMxNjI4MzktNTc0YTkxMjEtNmQ4MC00MDVkLTliOWMtMjRjYTFmMzc2YTQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI4VDE4MTU0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhNjZhNTg4N2UzNDQyMGVmZTdhMWM2NzI4OTlkNzgxMGI0ZTA3ODJkMjI5Y2NhMDg2MmFiOTVhMDBmOGUxYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fkvuEeH9FXRj7LSETbbYYEbb-ZzKrlVxjwWDSTBtQlc)

Probably, the domain zone registrar gives you more information because of the geo of your IP.
The whois.nic.ch service does not provide information from other countries.
