### ISSUE TITLE
Display only days left for domain expiration without additional information

### ISSUE THREAD

**Issue by mynameismudro** [click0/domain-check-2#38]
Hello!

Can this script show only how many days left for expiration, without any additional information?
For example:

./domain-check-2.sh -d github.com
286

Thanks.

**Comment by click0** [comment]
Hi.

 have no idea how to quickly display such information.
Inside the script, the DOMAINDIFF variable is responsible for displaying this information.

[This is](https://github.com/click0/domain-check-2/blob/820dcc434107fffdcd168d135419e7dd63428b6f/domain-check-2.sh#L1179C1-L1180C7) where you can insert the output of the DOMAINDIFF variable when calling the script with the additional `-q` argument.

```
prints "${DOMAINDIFF}"
```
